version: '3.9'

services:
  rpg_shop_db:
    container_name: rpg_shop_db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rpg_shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - my_network

  backend:
    image: payk96/rpgshop:0.0.1
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgresSQL
    restart: unless-stopped
    networks:
      - my_network


volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge